### ISSUE TITLE
Mejora los estilos y descomenta el normalize

### ISSUE THREAD

**Issue by alu0100786330** [alu0100786330/introduccion-ericconi-dsi-1516#2]
No es necesario comentar el normalize, ya que se sobreescribe pon los estilos en global.

**Comment by Alu0100673647** [comment]
Hola, @alu0100786330 ya he quitado los comentarios de index.html f49df5021849c7c6566f378f07104e583434afdc  y he puesto los estilos en el global.css 53f34846fb52c929324b931dcb6955f3cb9d0c4b
